In [24]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline

In [25]:
data =pd.read_csv("heart_attack_russia.csv")
data

,ID,Age,Gender,Region,Blood_Pressure,Cholesterol,BMI,Heart_Rate,Exercise_Level,Smoking,...,Income_Level,Physical_Activity,Education_Level,Marital_Status,Urban_Rural,Medication,Health_Awareness,Daily_Water_Intake,Mental_Health,Obesity
0,1,50,Male,Rural,110.0,196.5,15.9,76,High,False,...,Low,Low,Primary,Married,Rural,False,5,2.3,5,False
1,2,40,Female,Urban,138.8,157.5,27.1,82,Moderate,False,...,Low,Moderate,Higher,Married,Urban,False,1,5.0,4,False
2,3,26,Male,Rural,116.0,210.1,27.2,71,Moderate,False,...,Middle,High,Primary,Married,Urban,False,4,2.4,8,False
3,4,54,Female,Rural,133.5,170.5,26.0,74,Moderate,True,...,Middle,Moderate,Higher,Married,Urban,False,2,2.7,6,True
4,5,19,Female,Urban,108.0,224.5,27.5,67,Low,False,...,Middle,Low,Higher,Widowed,Urban,False,4,3.5,4,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49996,56,Other,Rural,87.7,256.8,25.3,71,Low,True,...,Middle,High,Primary,Divorced,Urban,True,4,4.9,1,False
49996,49997,16,Male,Rural,125.2,102.9,25.1,77,Moderate,True,...,Middle,High,Secondary,Single,Urban,False,3,4.4,4,True
49997,49998,46,Female,Suburban,116.2,160.6,27.7,63,Low,True,...,Middle,Low,Secondary,Single,Urban,False,2,2.4,7,False
49998,49999,24,Female,Rural,104.6,180.4,29.2,60,Moderate,True,...,Low,Moderate,Primary,Widowed,Urban,False,3,3.1,5,False
49999,50000,38,Male,Urban,122.9,89.2,21.8,69,Moderate,False,...,Low,Moderate,Higher,Single,Urban,False,5,2.0,2,True

In [26]:
data.isnull().sum()
df=data.dropna()
df
df.isnull().sum()

ID                       0
Age                      0
Gender                   0
Region                   0
Blood_Pressure           0
Cholesterol              0
BMI                      0
Heart_Rate               0
Exercise_Level           0
Smoking                  0
Alcohol_Consumption      0
Diabetes                 0
Family_History           0
Stress_Level             0
Heart_Attack             0
Angina                   0
Heart_Disease_History    0
Diet                     0
Sleep_Hours              0
Occupation               0
Income_Level             0
Physical_Activity        0
Education_Level          0
Marital_Status           0
Urban_Rural              0
Medication               0
Health_Awareness         0
Daily_Water_Intake       0
Mental_Health            0
Obesity                  0
dtype: int64

In [27]:
df.columns

Index(['ID', 'Age', 'Gender', 'Region', 'Blood_Pressure', 'Cholesterol', 'BMI',
       'Heart_Rate', 'Exercise_Level', 'Smoking', 'Alcohol_Consumption',
       'Diabetes', 'Family_History', 'Stress_Level', 'Heart_Attack', 'Angina',
       'Heart_Disease_History', 'Diet', 'Sleep_Hours', 'Occupation',
       'Income_Level', 'Physical_Activity', 'Education_Level',
       'Marital_Status', 'Urban_Rural', 'Medication', 'Health_Awareness',
       'Daily_Water_Intake', 'Mental_Health', 'Obesity'],
      dtype='object')

In [41]:
df["Heart_Attack"]
from sklearn.preprocessing import LabelEncoder
encoder =LabelEncoder()
df["Attack"]=encoder.fit_transform(df["Heart_Attack"])
df["Attack"]
df=df.drop("Heart_Attack",axis=1)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_15820\1580859704.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Attack"]=encoder.fit_transform(df["Heart_Attack"])

In [42]:
x =df.drop(columns=["Attack"],)
y =df["Attack"]

In [43]:
y

0        0
2        0
3        0
6        1
8        1
        ..
49994    0
49995    0
49997    0
49998    1
49999    0
Name: Attack, Length: 24976, dtype: int64

In [47]:
x.describe

<bound method NDFrame.describe of           ID  Age  Gender    Region  Blood_Pressure  Cholesterol   BMI  \
0          1   50    Male     Rural           110.0        196.5  15.9
2          3   26    Male     Rural           116.0        210.1  27.2
3          4   54  Female     Rural           133.5        170.5  26.0
6          7   50    Male  Suburban           116.8        206.9  27.9
8          9   34    Male     Urban           131.8        244.6  24.4
...      ...  ...     ...       ...             ...          ...   ...
49994  49995   37    Male     Rural           137.2        163.2  22.2
49995  49996   56   Other     Rural            87.7        256.8  25.3
49997  49998   46  Female  Suburban           116.2        160.6  27.7
49998  49999   24  Female     Rural           104.6        180.4  29.2
49999  50000   38    Male     Urban           122.9         89.2  21.8

       Heart_Rate Exercise_Level  Smoking  ... Income_Level  \
0              76           High    False  ...          Low
2              71       Moderate    False  ...       Middle
3              74       Moderate     True  ...       Middle
6              75           High     True  ...       Middle
8              65            Low    False  ...         High
...           ...            ...      ...  ...          ...
49994          91            Low     True  ...          Low
49995          71            Low     True  ...       Middle
49997          63            Low     True  ...       Middle
49998          60       Moderate     True  ...          Low
49999          69       Moderate    False  ...          Low

       Physical_Activity  Education_Level  Marital_Status  Urban_Rural  \
0                    Low          Primary         Married        Rural
2                   High          Primary         Married        Urban
3               Moderate           Higher         Married        Urban
6               Moderate          Primary         Married        Urban
8               Moderate          Primary         Married        Rural
...                  ...              ...             ...          ...
49994           Moderate           Higher          Single        Urban
49995               High          Primary        Divorced        Urban
49997                Low        Secondary          Single        Urban
49998           Moderate          Primary         Widowed        Urban
49999           Moderate           Higher          Single        Urban

       Medication Health_Awareness  Daily_Water_Intake Mental_Health Obesity
0           False                5                 2.3             5   False
2           False                4                 2.4             8   False
3           False                2                 2.7             6    True
6            True                1                 1.7            10    True
8           False                1                 4.7             7   False
...           ...              ...                 ...           ...     ...
49994       False                2                 3.6             4   False
49995        True                4                 4.9             1   False
49997       False                2                 2.4             7   False
49998       False                3                 3.1             5   False
49999       False                5                 2.0             2    True

[24976 rows x 29 columns]>

In [48]:
from sklearn.preprocessing import LabelEncoder

# Initialize LabelEncoder
label_encoder = LabelEncoder()

# List of categorical columns to encode
categorical_columns = ['Gender', 'Region', 'Exercise_Level', 'Smoking', 'Income_Level', 
                       'Physical_Activity', 'Education_Level', 'Marital_Status', 
                       'Urban_Rural', 'Medication', 'Health_Awareness', 'Mental_Health', 'Obesity']

# Apply label encoding to each categorical column
for col in categorical_columns:
    df[col] = label_encoder.fit_transform(df[col])

# Check the transformed DataFrame
print(df.head())

   ID  Age  Gender  Region  Blood_Pressure  Cholesterol   BMI  Heart_Rate  \
0   1   50       1       0           110.0        196.5  15.9          76
2   3   26       1       0           116.0        210.1  27.2          71
3   4   54       0       0           133.5        170.5  26.0          74
6   7   50       1       1           116.8        206.9  27.9          75
8   9   34       1       2           131.8        244.6  24.4          65

   Exercise_Level  Smoking  ... Physical_Activity  Education_Level  \
0               0        0  ...                 1                1
2               2        0  ...                 0                1
3               2        1  ...                 2                0
6               0        1  ...                 2                1
8               1        0  ...                 2                1

   Marital_Status  Urban_Rural  Medication  Health_Awareness  \
0               1            0           0                 4
2               1            1           0                 3
3               1            1           0                 1
6               1            1           1                 0
8               1            0           0                 0

  Daily_Water_Intake  Mental_Health Obesity  Attack
0                2.3              4       0       0
2                2.4              7       0       0
3                2.7              5       1       0
6                1.7              9       1       1
8                4.7              6       0       1

[5 rows x 30 columns]